### ISSUE TITLE
[FEAT] 칵테일 상세검색 뷰 - 자동완성 UI 구현

### ISSUE THREAD

**Issue by Suyeon9911** [TeamNobar/Nobar-iOS#25]
## 💡 Feature Issue

칵테일 상세 검색 뷰에서 자동완성 되는 부분의 ui와 기능을 구현하겠습니당 !

## 🌿  To-do

- [x] 글자 입력시 화면전환 : 자동완성되는 뷰로 넘어오기
- [x] 자동완성 기능 구현하기 
- [x] 자동완성 입력한 글자만 볼드체로 

** 각각 요소들 눌렀을 때 이동은 아직 기획단에서 확답을 안줬음
- [ ] 화면전환 시 , 입력 위치.. 조정 --> 해결 못한채로 일단.. 피알올리고 다른 작업 먼저 후딱끝내자잉
