### ISSUE TITLE
[FEAT] 최근 검색 기능 구현

### ISSUE THREAD

**Issue by Suyeon9911** [TeamNobar/Nobar-iOS#47]
## 💡 Feature Issue

최근 검색어 기능을 로컬 DB로 구현하고, Diffable Datasource로 바꿔볼 예정입니다 (리로드 섹션하니까 헤더까지 리로드되네요..)

## 🌿  To-do

- [x] 최근 검색어 기능 구현 
- [ ] DIffable DataSource로 변경 -> 나중에 하도록 하겠습니다요
- [x] 눌렀을 때 상세 레시피 페이지로 이동 -> 기능명세서 확인 ㅎ
