### ISSUE TITLE
[FEAT] 검색 디테일 기능 구현

### ISSUE THREAD

**Issue by Suyeon9911** [TeamNobar/Nobar-iOS#48]
## 💡 Feature Issue

추천 검색어에 오늘 날짜를 기준으로 라벨에 띄워주는게 있더라구요. 그 부분이랑 화면전환 연결 할 예정입니당 ~
자동완성 되었을때도 화면전환 구현합니당 ~ 

## 🌿  To-do

- [x] 오늘 날짜 기준으로 라벨 설정
- [x] 추천검색어 누를 시 어디로 ?? 기능명세서 고고
- [x] 자동완성 누를 시 어디로? 기능명세서 고고
